CREATE DATABASE Psales;

USE Psales;

-- CRIAR A TABELA DE CURSOS
CREATE TABLE Cursos
(
    -- NOME_COLUNA TIPO_DADO CHAVE_PRIMARY AUTO_INCRREMENTO
    IdCurso     INT PRIMARY KEY IDENTITY
    -- NOME_COLUNA TIPO_DADO
    ,Nome       VARCHAR(200) NOT NULL UNIQUE
);

-- CRIAR A TABELA DE DISCIPLINAS
CREATE TABLE Disciplinas
(
    IdMateria       INT PRIMARY KEY IDENTITY
    ,Nome           VARCHAR(200)
    ,IdCurso        INT FOREIGN KEY REFERENCES Cursos (IdCurso)
);

-- CRIAR A TABELA DE ALUNOS
CREATE TABLE Alunos
(
    IdAluno         INT PRIMARY KEY IDENTITY
    ,Nome           VARCHAR(200) NOT NULL
);

-- CRIAR A TABELA PARA MATRICULAR OS ALUNOS EM SEUS DETERMINADOS CURSOS
CREATE TABLE CursosAlunos
(
    IdCurso     INT FOREIGN KEY REFERENCES Cursos (IdCurso)
    ,IdAluno    INT FOREIGN KEY REFERENCES Alunos (IdAluno)
);